src/main/java/cn/com/yyg/base/entity/ProductEntity.java
package cn.com.yyg.base.entity;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang3.StringUtils;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import cn.com.easy.persistence.BaseEntity;
import cn.com.easy.utils.FastJSONUtils;
import cn.com.easy.utils.SpringContextHolder;
import cn.com.yyg.front.dto.ProductPhotoDto;
//import cn.com.yyg.front.dto.ProductPhotoDto;
import cn.com.yyg.front.utils.BaseConfig;

import com.google.common.collect.Lists;

/**
 * 商品表
 * 
 * @author lvzf 2016年8月19日
 * 
 */
@Entity
@Table(name = "yyg_product")
@DynamicInsert
@DynamicUpdate
public class ProductEntity extends BaseEntity {
	/** */
	private static final long serialVersionUID = 5000581615498043411L;
	/** 上架 */
	public static final int STATUS_UP = 1;
	/** 下架 */
	public static final int STATUS_DOWN = 0;

	/** 商品名称 */
	@Column(nullable = false, columnDefinition = "varchar(500) COMMENT '商品名称'")
	private String name;
	/** 商品副标题 */
	@Column(columnDefinition = "varchar(500) COMMENT '商品副标题'")
	private String title;
	/** 原价格 */
	@Column(nullable = false, columnDefinition = " bigint default 0 ")
	private long origPrice;
	/** 单次购买价格 */
	@Column(nullable = false, columnDefinition = " bigint default 0 ")
	private long singlePrice;
	/** 总份数（总人次） */
	@Column(nullable = false, columnDefinition = " bigint default 0 ")
	private long totalNum;
	/** 最大期数 */
	private Long limitPeriods=500L;
	/** 当前期数 */
	@Column(nullable = false, columnDefinition = " bigint default 0 ")
	private long period=0;
	/** 状态：0-上架，1-下架 */
	private int status;
	/** 封面图路径 */
	private String logoPath;
	/** 商品图集 */
	@Column(columnDefinition = " varchar(3000) ")
	private String photos;

	public List<ProductPhotoDto> getPhotoList(){
		if(StringUtils.isNoneBlank(photos)){
			return FastJSONUtils.toArray(photos, ProductPhotoDto.class);
		}
		return Lists.newArrayList();
	}

	/** 保存到内容表 ContentEntity */
	private Long contentId;
	/** 内容 */
	@Transient
	private String content;

	private String seoTitle;
	private String seoKey;
	private String seoDesc;

	public String getStatusName() {
		if (status == 1) {
			return "上架";
		} else if (status == 0) {
			return "下架";
		}
		return "";
	}

	/** 所属品牌 */
	private Long brandId;
	/** 所属分类 productType表 */
	private String cateId;

	/** 推荐 */
	@Column(nullable = false, columnDefinition = " bit default 0 ")
	private boolean recommend;
	/** 排序号（人气） */
	@Column(nullable = false, columnDefinition = " bigint default 50 ")
	private int seqNo;

 

	/**
	 * get name  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getName() {
		return name;
	}



	/** 
	 *set name
	 * @param name 
	 * @author lvzf 2016年8月27日
	 */
	public void setName(String name) {
		this.name = name;
	}



	/**
	 * get title  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getTitle() {
		return title;
	}



	/** 
	 *set title
	 * @param title 
	 * @author lvzf 2016年8月27日
	 */
	public void setTitle(String title) {
		this.title = title;
	}



	/**
	 * get origPrice  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public long getOrigPrice() {
		return origPrice;
	}



	/** 
	 *set origPrice
	 * @param origPrice 
	 * @author lvzf 2016年8月27日
	 */
	public void setOrigPrice(long origPrice) {
		this.origPrice = origPrice;
	}




	/**
	 * get singlePrice  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public long getSinglePrice() {
		return singlePrice;
	}



	/** 
	 *set singlePrice
	 * @param singlePrice 
	 * @author lvzf 2016年8月27日
	 */
	public void setSinglePrice(long singlePrice) {
		this.singlePrice = singlePrice;
	}



	/**
	 * get totalNum  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public long getTotalNum() {
		return totalNum;
	}



	/** 
	 *set totalNum
	 * @param totalNum 
	 * @author lvzf 2016年8月27日
	 */
	public void setTotalNum(long totalNum) {
		this.totalNum = totalNum;
	}



	/**
	 * get limitPeriods  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getLimitPeriods() {
		return limitPeriods;
	}



	/** 
	 *set limitPeriods
	 * @param limitPeriods 
	 * @author lvzf 2016年8月27日
	 */
	public void setLimitPeriods(Long limitPeriods) {
		this.limitPeriods = limitPeriods;
	}



	/**
	 * get period  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public long getPeriod() {
		return period;
	}



	/** 
	 *set period
	 * @param period 
	 * @author lvzf 2016年8月27日
	 */
	public void setPeriod(long period) {
		this.period = period;
	}



	/**
	 * get status  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public int getStatus() {
		return status;
	}



	/** 
	 *set status
	 * @param status 
	 * @author lvzf 2016年8月27日
	 */
	public void setStatus(int status) {
		this.status = status;
	}



	/**
	 * get photos  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getPhotos() {
		return photos;
	}



	/** 
	 *set photos
	 * @param photos 
	 * @author lvzf 2016年8月27日
	 */
	public void setPhotos(String photos) {
		this.photos = photos;
	}



	/**
	 * get contentId  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getContentId() {
		return contentId;
	}



	/** 
	 *set contentId
	 * @param contentId 
	 * @author lvzf 2016年8月27日
	 */
	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}



	/**
	 * get content  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getContent() {
		return content;
	}



	/** 
	 *set content
	 * @param content 
	 * @author lvzf 2016年8月27日
	 */
	public void setContent(String content) {
		this.content = content;
	}



	/**
	 * get seoTitle  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getSeoTitle() {
		return seoTitle;
	}



	/** 
	 *set seoTitle
	 * @param seoTitle 
	 * @author lvzf 2016年8月27日
	 */
	public void setSeoTitle(String seoTitle) {
		this.seoTitle = seoTitle;
	}



	/**
	 * get seoKey  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getSeoKey() {
		return seoKey;
	}



	/** 
	 *set seoKey
	 * @param seoKey 
	 * @author lvzf 2016年8月27日
	 */
	public void setSeoKey(String seoKey) {
		this.seoKey = seoKey;
	}



	/**
	 * get seoDesc  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getSeoDesc() {
		return seoDesc;
	}



	/** 
	 *set seoDesc
	 * @param seoDesc 
	 * @author lvzf 2016年8月27日
	 */
	public void setSeoDesc(String seoDesc) {
		this.seoDesc = seoDesc;
	}



	/**
	 * get brandId  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getBrandId() {
		return brandId;
	}



	/** 
	 *set brandId
	 * @param brandId 
	 * @author lvzf 2016年8月27日
	 */
	public void setBrandId(Long brandId) {
		this.brandId = brandId;
	}



	/**
	 * get cateId  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getCateId() {
		return cateId;
	}



	/** 
	 *set cateId
	 * @param cateId 
	 * @author lvzf 2016年8月27日
	 */
	public void setCateId(String cateId) {
		this.cateId = cateId;
	}



	/**
	 * get recommend  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public boolean isRecommend() {
		return recommend;
	}



	/** 
	 *set recommend
	 * @param recommend 
	 * @author lvzf 2016年8月27日
	 */
	public void setRecommend(boolean recommend) {
		this.recommend = recommend;
	}



	/**
	 * get seqNo  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public int getSeqNo() {
		return seqNo;
	}



	/** 
	 *set seqNo
	 * @param seqNo 
	 * @author lvzf 2016年8月27日
	 */
	public void setSeqNo(int seqNo) {
		this.seqNo = seqNo;
	}



	/** 
	 *set logoPath
	 * @param logoPath 
	 * @author lvzf 2016年8月27日
	 */
	public void setLogoPath(String logoPath) {
		this.logoPath = logoPath;
	}



	/**
	 * get logoPath
	 * 
	 * @return
	 * @author lvzf 2016年8月19日
	 */
	public String getLogoPath() {	
		if(StringUtils.isBlank(logoPath)){
			return null;
		}
		if (logoPath.startsWith("http")) {
			return logoPath;
		} 
		BaseConfig baseConfig = SpringContextHolder.getBean(BaseConfig.class);
		return baseConfig.getImgServerUrl() + logoPath;
	}

	 

}

src/main/java/cn/com/yyg/base/entity/UserYgEntity.java
package cn.com.yyg.base.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import cn.com.easy.persistence.BaseEntity;
/**
 * 用户云购商品记录表
 * @author lvzf	2016年8月19日
 *
 */
@Entity
@Table(name = "yyg_user_yg")
@DynamicInsert
@DynamicUpdate
public class UserYgEntity  extends BaseEntity{  
	/** */
	private static final long serialVersionUID = -5434273269333615583L;
	/**商品id*/ 
    private Long productId;
	/**云购商品id*/ 
    private Long ygProductId;
	/**云购商品*/ 
    @Transient
    private YgProductEntity ygProduct;
	/**当前期数*/ 
	@Column(columnDefinition = "int COMMENT '当前期数'")
	private long period;
	/**商品名称*/ 
	@Column(nullable = false,columnDefinition = "varchar(500) COMMENT '商品名称'")
	private String productName; 
	/** 总份数（总人次） */
	@Column(nullable = false, columnDefinition = " bigint default 0 ")
	private long totalNum;
	/**单次购买价格*/ 
	@Column(nullable = false, columnDefinition = "bigint default 0 COMMENT '单次购买价格'")
	private long singlePrice;
	/**云购用户id*/ 
	private Long buyUserId;
	/**云购用户昵称*/ 
	private String buyUserNickName;

	/**云购用户头像*/ 
	private String buyUserLogoPath;
	/**购买份数*/  
	@Column(nullable = false, columnDefinition = "bigint default 0 COMMENT '购买份数'")
	private long buyNum; 

	/**状态：0-未领奖，1-已领奖*/
	@Column(columnDefinition = "int default 0 COMMENT '状态：0-未领奖，1-已领奖'")
	private int status; 
	public String getStatusName(){
		return (status==0)?"未领奖":"已领奖";
	}	 
	/**购买（夺宝）时间*/ 
	@Column(columnDefinition = "bigint COMMENT '购买时间'")
	private Long buyDateLong; 
	/**购买（夺宝）时间*/ 
	public Date getBuyDate(){
		if(buyDateLong==null){
			return null;
		}
		return new Date(buyDateLong);
	}
	/**随机购买的云购号码*/ 
	@Column(columnDefinition = "longtext COMMENT '随机购买的云购号码'")
	private String buyNos; 

	/**是否中奖*/ 
	@Column(columnDefinition = "bit default false COMMENT '是否中奖'")
	private boolean win;
	/**中奖号码*/ 
	@Column(columnDefinition = "bigint COMMENT '中奖号码'")
	private Long winNo; 
	
	/**支付交易id：支付完成才生成购买号码*/ 
	@Column(columnDefinition = "bigint COMMENT '支付交易id'")
	private Long payTradeId;
	/**客户端ip*/
	private String clientIp; 

	/**ip地址*/
	private String ipAddr; 
	/**
	 * get productId  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getProductId() {
		return productId;
	}

	/** 
	 *set productId
	 * @param productId 
	 * @author lvzf 2016年8月27日
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * get ygProductId  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getYgProductId() {
		return ygProductId;
	}

	/** 
	 *set ygProductId
	 * @param ygProductId 
	 * @author lvzf 2016年8月27日
	 */
	public void setYgProductId(Long ygProductId) {
		this.ygProductId = ygProductId;
	}

	/**
	 * get period  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public long getPeriod() {
		return period;
	}

	/** 
	 *set period
	 * @param period 
	 * @author lvzf 2016年8月27日
	 */
	public void setPeriod(long period) {
		this.period = period;
	}

	/**
	 * get productName  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getProductName() {
		return productName;
	}

	/** 
	 *set productName
	 * @param productName 
	 * @author lvzf 2016年8月27日
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

 

	/**
	 * get totalNum  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public long getTotalNum() {
		return totalNum;
	}

	/** 
	 *set totalNum
	 * @param totalNum 
	 * @author lvzf 2016年8月27日
	 */
	public void setTotalNum(long totalNum) {
		this.totalNum = totalNum;
	}

	/**
	 * get singlePrice  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public long getSinglePrice() {
		return singlePrice;
	}

	/** 
	 *set singlePrice
	 * @param singlePrice 
	 * @author lvzf 2016年8月27日
	 */
	public void setSinglePrice(long singlePrice) {
		this.singlePrice = singlePrice;
	}

	/**
	 * get buyUserId  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getBuyUserId() {
		return buyUserId;
	}

	/** 
	 *set buyUserId
	 * @param buyUserId 
	 * @author lvzf 2016年8月27日
	 */
	public void setBuyUserId(Long buyUserId) {
		this.buyUserId = buyUserId;
	}

	/**
	 * get buyUserNickName  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getBuyUserNickName() {
		return buyUserNickName;
	}

	/** 
	 *set buyUserNickName
	 * @param buyUserNickName 
	 * @author lvzf 2016年8月27日
	 */
	public void setBuyUserNickName(String buyUserNickName) {
		this.buyUserNickName = buyUserNickName;
	}

	/**
	 * get buyNum  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public long getBuyNum() {
		return buyNum;
	}

	/** 
	 *set buyNum
	 * @param buyNum 
	 * @author lvzf 2016年8月27日
	 */
	public void setBuyNum(long buyNum) {
		this.buyNum = buyNum;
	}

	/**
	 * get status  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public int getStatus() {
		return status;
	}

	/** 
	 *set status
	 * @param status 
	 * @author lvzf 2016年8月27日
	 */
	public void setStatus(int status) {
		this.status = status;
	}

	/**
	 * get buyDateLong  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getBuyDateLong() {
		return buyDateLong;
	}

	/** 
	 *set buyDateLong
	 * @param buyDateLong 
	 * @author lvzf 2016年8月27日
	 */
	public void setBuyDateLong(Long buyDateLong) {
		this.buyDateLong = buyDateLong;
	}

	/**
	 * get buyNos  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getBuyNos() {
		return buyNos;
	}

	/** 
	 *set buyNos
	 * @param buyNos 
	 * @author lvzf 2016年8月27日
	 */
	public void setBuyNos(String buyNos) {
		this.buyNos = buyNos;
	}

	/**
	 * get win  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public boolean isWin() {
		return win;
	}

	/** 
	 *set win
	 * @param win 
	 * @author lvzf 2016年8月27日
	 */
	public void setWin(boolean win) {
		this.win = win;
	}

	/**
	 * get winNo  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getWinNo() {
		return winNo;
	}

	/** 
	 *set winNo
	 * @param winNo 
	 * @author lvzf 2016年8月27日
	 */
	public void setWinNo(Long winNo) {
		this.winNo = winNo;
	}

	/**
	 * get payTradeId  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getPayTradeId() {
		return payTradeId;
	}

	/** 
	 *set payTradeId
	 * @param payTradeId 
	 * @author lvzf 2016年8月27日
	 */
	public void setPayTradeId(Long payTradeId) {
		this.payTradeId = payTradeId;
	}

	/**
	 * get buyUserLogoPath  
	 * @return   
	 * @author lvzf 2016年8月29日
	 */
	public String getBuyUserLogoPath() {
		return buyUserLogoPath;
	}

	/** 
	 *set buyUserLogoPath
	 * @param buyUserLogoPath 
	 * @author lvzf 2016年8月29日
	 */
	public void setBuyUserLogoPath(String buyUserLogoPath) {
		this.buyUserLogoPath = buyUserLogoPath;
	}

	/**
	 * get clientIp  
	 * @return   
	 * @author lvzf 2016年9月5日
	 */
	public String getClientIp() {
		return clientIp;
	}

	/** 
	 *set clientIp
	 * @param clientIp 
	 * @author lvzf 2016年9月5日
	 */
	public void setClientIp(String clientIp) {
		this.clientIp = clientIp;
	}

	/**
	 * get ipAddr  
	 * @return   
	 * @author lvzf 2016年9月5日
	 */
	public String getIpAddr() {
		return ipAddr;
	}

	/** 
	 *set ipAddr
	 * @param ipAddr 
	 * @author lvzf 2016年9月5日
	 */
	public void setIpAddr(String ipAddr) {
		this.ipAddr = ipAddr;
	}

	/**
	 * get ygProduct  
	 * @return   
	 * @author lvzf 2016年9月25日
	 */
	public YgProductEntity getYgProduct() {
		return ygProduct;
	}

	/** 
	 *set ygProduct
	 * @param ygProduct 
	 * @author lvzf 2016年9月25日
	 */
	public void setYgProduct(YgProductEntity ygProduct) {
		this.ygProduct = ygProduct;
	}
 
	
}

src/main/java/cn/com/yyg/front/web/pub/controller/CaptchaController.java
/**
 * 
 */
package cn.com.yyg.front.web.pub.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import cn.com.yyg.front.utils.CaptchaUtils;

/**
 * 验证码控制类
 * 
 * @author nibili 2015年10月25日下午9:01:15
 * 
 */
@Controller
@RequestMapping("/captcha")
public class CaptchaController {
	/**
	 * 获取验证码
	 * 
	 * @param request
	 * @param response
	 * @throws Exception
	 * @auth nibili 2015年8月28日 下午3:59:10
	 */
	@RequestMapping(value = "", method = RequestMethod.GET)
	public void getCaptcha(HttpServletRequest request, HttpServletResponse response) throws Exception {
		CaptchaUtils.sendCaptcha(request, response);
	}

}

src/main/webapp/WEB-INF/pages/pub/product/product_buy_record.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ include file="../../commons/taglibs.jsp"%>
<c:choose>
 <c:when test="${empty resultMap}">
  <div class="empty">
   <p class="status-empty">
    <i class="littleU littleU-cry"></i>
    &nbsp;&nbsp;暂时还没有参与记录！
   </p>
  </div>
 </c:when>
 <c:otherwise>
  <div class="content" style="">
   <div class="m-detail-recordList-start">
    <i class="ico ico-clock"></i>
   </div>
   <c:forEach items="${resultMap}" var="map">
    <div class="m-detail-recordList-timeSeperate">
     ${map.key }
     <i class="ico ico-recordDot ico-recordDot-solid"></i>
    </div>
    <ul class="m-detail-recordList m-detail-recordList-0">
     <c:forEach items="${map.value}" var="val">
      <li class="f-clear">
       <span class="time">
        <fmt:formatDate value="${val.buyDate }" pattern="HH:mm:ss.SSS" />
       </span>
       <i class="ico ico-recordDot ico-recordDot-hollow"></i>
       <div class="m-detail-recordList-userInfo">
        <div class="inner">
         <p>
          <span class="avatar">
          <c:if test="${not empty val.buyUserLogoPath}">
           <img height="20" src="${val.buyUserLogoPath}" width="20">
           </c:if>
          </span>
          <a href="/user/${val.buyUserId}" target="_blank" class="color02">${val.buyUserNickName }</a>
          (${val.ipAddr } IP：${val.clientIp }) 参与了
          <b class="times txt-red">${val.buyNum }人次</b>
          <a class="w-button w-button-simple btn-checkCodes" data-func="code" data-rid="1027" href="javascript:void(0)" style="display: none;">
           所有云购号码
           <i class="ico ico-arrow-gray ico-arrow-gray-down"></i>
          </a>
         </p>
         <a class="btn-close" href="javascript:void(0)" style="display: none;">x</a>
         <p class="codes" style="display: none;">
          <c:set value="${ fn:split(val.buyNos,',') }" var="buyNos" />
          <c:forEach items="${buyNos}" var="buyNo">
           <b <c:if test="${buyNo eq val.winNo}">style="color:#E54048; font-weight:bold;"</c:if>>${buyNo }</b>
          </c:forEach>
         </p>
        </div>
       </div>
      </li>
     </c:forEach>
    </ul>
   </c:forEach>
  </div>
  <%@ include file="../commons/page.jsp"%>
  <script type="text/javascript">
    //查看购买号码
    $(".btn-checkCodes").click(function(){
  	  $(this).closest(".f-clear").addClass("m-detail-recordList-userInfo-detail");
    });
    $(".btn-close").click(function(){
  	  $(this).closest(".f-clear").removeClass("m-detail-recordList-userInfo-detail");
    });
    $(".w-pager button").click(function() {
    	loadBuyRecord($(this).attr("pageNo"));
    });
  </script>
 </c:otherwise>
</c:choose>

src/main/webapp/WEB-INF/pages/pub/product/product_period_page.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ include file="../../commons/taglibs.jsp"%>
<c:set var="nowPageNo" value="${page.pageNo}" />
<%--设置总页数--%>
<c:set var="totalPage" value="${page.totalPages}"></c:set>
<div class="m-detail-period-list f-clear">
 <ul class="list f-clear" id="ul_periods">
  <c:forEach items="${page.result }" var="period" varStatus="status">
   <li <c:if test="${period.period ==product.period}">class="curr"</c:if>>
    <a href="/product/${period.id}.html">第${period.period}期</a>
   </li>
  </c:forEach>
 </ul>
</div>
<div id="pro-view-3" class="w-pager w-pager-simple">
 <a class="w-button w-pager-prev w-button-aside<c:if test="${nowPageNo==1}"> w-button-disabled</c:if>" pageNo="${nowPageNo-1}" id="bt_page_pre">上一页</a>
 <a class="w-button w-pager-next w-button-aside<c:if test="${nowPageNo==totalPage}"> w-button-disabled</c:if>" pageNo="${nowPageNo+1}" id="bt_page_next">下一页</a>
</div>
<script type="text/javascript">
	$("#pro-view-3 .w-button").click(function() {
		if($(this).attr("class").indexOf("w-button-disabled")<0){
			loadPeriodPage($(this).attr("pageNo"));
		}
	});
</script>

src/main/webapp/WEB-INF/pages/pub/product/product_share_record.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ include file="../../commons/taglibs.jsp"%>
<c:choose>
 <c:when test="${empty page.result}">
  <div class="empty">
   <p class="status-empty">
    <i class="littleU littleU-cry"></i>
    &nbsp;&nbsp;暂时还没有任何晒单
   </p>
  </div>
 </c:when>
 <c:otherwise>
  <div class="content" style="">
   <ul class="m-detail-shareList-list">
    <c:forEach items="${page.result }" var="item">
     <li>
      <div class="m-detail-shareList-author">
       <a class="avatar" href="/user/${item.userId}" target="_blank">
        <img height="90" src="${item.userLogoPath }" width="90">
       </a>
       <a class="nickname f-txtabb" href="/user/${item.userId}" target="_blank" title="BianZX">${item.userNickName}</a>
      </div>
      <div class="m-detail-shareList-detail">
       <i class="ico ico-arrow ico-arrow-grayShareArr"></i>
       <div class="titleWrap">
        <span class="date">
         <fmt:formatDate value="${item.createTime }" pattern="yyyy-MM-dd HH:mm:ss" />
        </span>
        <span class="title">
         第${item.period }期晒单
         <a href="/share/${item.id }.html" target="_blank">
          <b>${item.title }</b>
         </a>
        </span>
       </div>
       <div class="contentWrap">
        <a href="/share/${item.id }.html" target="_blank"> ${item.content } </a>
       </div>
       <div class="imgWrap">
        <c:forEach items="${item.photoList }" var="photo">
         <a href="/share/${item.id }.html" target="_blank">
          <div style="display: table-cell; writing-mode: tb-rl; height: 140px; line-height: 140px; vertical-align: middle">
           <img src="${photo}" width="140">
          </div>
         </a>
        </c:forEach>
       </div>
      </div>
     </li>
    </c:forEach>
   </ul>
  </div>
  <%@ include file="../commons/page.jsp"%>
  <script type="text/javascript">
			$(".w-pager button").click(function() {
				loadShareRecord($(this).attr("pageNo"));
			});
		</script>
 </c:otherwise>
</c:choose>