src/main/java/cn/com/yyg/base/entity/UserYgEntity.java
package cn.com.yyg.base.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import cn.com.easy.persistence.BaseEntity;
/**
 * 用户云购商品记录表
 * @author lvzf	2016年8月19日
 *
 */
@Entity
@Table(name = "yyg_user_yg")
@DynamicInsert
@DynamicUpdate
public class UserYgEntity  extends BaseEntity{  
	/** */
	private static final long serialVersionUID = -5434273269333615583L;
	/**商品id*/ 
    private Long productId;
	/**云购商品id*/ 
    private Long ygProductId;
	/**云购商品*/ 
    @Transient
    private YgProductEntity ygProduct;
	/**当前期数*/ 
	@Column(columnDefinition = "int COMMENT '当前期数'")
	private long period;
	/**商品名称*/ 
	@Column(nullable = false,columnDefinition = "varchar(500) COMMENT '商品名称'")
	private String productName; 
	/** 总份数（总人次） */
	@Column(nullable = false, columnDefinition = " bigint default 0 ")
	private long totalNum;
	/**单次购买价格*/ 
	@Column(nullable = false, columnDefinition = "bigint default 0 COMMENT '单次购买价格'")
	private long singlePrice;
	/**云购用户id*/ 
	private Long buyUserId;
	/**云购用户昵称*/ 
	private String buyUserNickName;

	/**云购用户头像*/ 
	private String buyUserLogoPath;
	/**购买份数*/  
	@Column(nullable = false, columnDefinition = "bigint default 0 COMMENT '购买份数'")
	private long buyNum; 

	/**状态：0-未领奖，1-已领奖*/
	@Column(columnDefinition = "int default 0 COMMENT '状态：0-未领奖，1-已领奖'")
	private int status; 
	public String getStatusName(){
		return (status==0)?"未领奖":"已领奖";
	}	 
	/**购买（夺宝）时间*/ 
	@Column(columnDefinition = "bigint COMMENT '购买时间'")
	private Long buyDateLong; 
	/**购买（夺宝）时间*/ 
	public Date getBuyDate(){
		if(buyDateLong==null){
			return null;
		}
		return new Date(buyDateLong);
	}
	/**随机购买的云购号码*/ 
	@Column(columnDefinition = "longtext COMMENT '随机购买的云购号码'")
	private String buyNos; 

	/**是否中奖*/ 
	@Column(columnDefinition = "bit default false COMMENT '是否中奖'")
	private boolean win;
	/**中奖号码*/ 
	@Column(columnDefinition = "bigint COMMENT '中奖号码'")
	private Long winNo; 
	
	/**支付交易id：支付完成才生成购买号码*/ 
	@Column(columnDefinition = "bigint COMMENT '支付交易id'")
	private Long payTradeId;
	/**客户端ip*/
	private String clientIp; 

	/**ip地址*/
	private String ipAddr; 
	/**
	 * get productId  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getProductId() {
		return productId;
	}

	/** 
	 *set productId
	 * @param productId 
	 * @author lvzf 2016年8月27日
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * get ygProductId  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getYgProductId() {
		return ygProductId;
	}

	/** 
	 *set ygProductId
	 * @param ygProductId 
	 * @author lvzf 2016年8月27日
	 */
	public void setYgProductId(Long ygProductId) {
		this.ygProductId = ygProductId;
	}

	/**
	 * get period  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public long getPeriod() {
		return period;
	}

	/** 
	 *set period
	 * @param period 
	 * @author lvzf 2016年8月27日
	 */
	public void setPeriod(long period) {
		this.period = period;
	}

	/**
	 * get productName  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getProductName() {
		return productName;
	}

	/** 
	 *set productName
	 * @param productName 
	 * @author lvzf 2016年8月27日
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

 

	/**
	 * get totalNum  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public long getTotalNum() {
		return totalNum;
	}

	/** 
	 *set totalNum
	 * @param totalNum 
	 * @author lvzf 2016年8月27日
	 */
	public void setTotalNum(long totalNum) {
		this.totalNum = totalNum;
	}

	/**
	 * get singlePrice  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public long getSinglePrice() {
		return singlePrice;
	}

	/** 
	 *set singlePrice
	 * @param singlePrice 
	 * @author lvzf 2016年8月27日
	 */
	public void setSinglePrice(long singlePrice) {
		this.singlePrice = singlePrice;
	}

	/**
	 * get buyUserId  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getBuyUserId() {
		return buyUserId;
	}

	/** 
	 *set buyUserId
	 * @param buyUserId 
	 * @author lvzf 2016年8月27日
	 */
	public void setBuyUserId(Long buyUserId) {
		this.buyUserId = buyUserId;
	}

	/**
	 * get buyUserNickName  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getBuyUserNickName() {
		return buyUserNickName;
	}

	/** 
	 *set buyUserNickName
	 * @param buyUserNickName 
	 * @author lvzf 2016年8月27日
	 */
	public void setBuyUserNickName(String buyUserNickName) {
		this.buyUserNickName = buyUserNickName;
	}

	/**
	 * get buyNum  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public long getBuyNum() {
		return buyNum;
	}

	/** 
	 *set buyNum
	 * @param buyNum 
	 * @author lvzf 2016年8月27日
	 */
	public void setBuyNum(long buyNum) {
		this.buyNum = buyNum;
	}

	/**
	 * get status  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public int getStatus() {
		return status;
	}

	/** 
	 *set status
	 * @param status 
	 * @author lvzf 2016年8月27日
	 */
	public void setStatus(int status) {
		this.status = status;
	}

	/**
	 * get buyDateLong  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getBuyDateLong() {
		return buyDateLong;
	}

	/** 
	 *set buyDateLong
	 * @param buyDateLong 
	 * @author lvzf 2016年8月27日
	 */
	public void setBuyDateLong(Long buyDateLong) {
		this.buyDateLong = buyDateLong;
	}

	/**
	 * get buyNos  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public String getBuyNos() {
		return buyNos;
	}

	/** 
	 *set buyNos
	 * @param buyNos 
	 * @author lvzf 2016年8月27日
	 */
	public void setBuyNos(String buyNos) {
		this.buyNos = buyNos;
	}

	/**
	 * get win  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public boolean isWin() {
		return win;
	}

	/** 
	 *set win
	 * @param win 
	 * @author lvzf 2016年8月27日
	 */
	public void setWin(boolean win) {
		this.win = win;
	}

	/**
	 * get winNo  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getWinNo() {
		return winNo;
	}

	/** 
	 *set winNo
	 * @param winNo 
	 * @author lvzf 2016年8月27日
	 */
	public void setWinNo(Long winNo) {
		this.winNo = winNo;
	}

	/**
	 * get payTradeId  
	 * @return   
	 * @author lvzf 2016年8月27日
	 */
	public Long getPayTradeId() {
		return payTradeId;
	}

	/** 
	 *set payTradeId
	 * @param payTradeId 
	 * @author lvzf 2016年8月27日
	 */
	public void setPayTradeId(Long payTradeId) {
		this.payTradeId = payTradeId;
	}

	/**
	 * get buyUserLogoPath  
	 * @return   
	 * @author lvzf 2016年8月29日
	 */
	public String getBuyUserLogoPath() {
		return buyUserLogoPath;
	}

	/** 
	 *set buyUserLogoPath
	 * @param buyUserLogoPath 
	 * @author lvzf 2016年8月29日
	 */
	public void setBuyUserLogoPath(String buyUserLogoPath) {
		this.buyUserLogoPath = buyUserLogoPath;
	}

	/**
	 * get clientIp  
	 * @return   
	 * @author lvzf 2016年9月5日
	 */
	public String getClientIp() {
		return clientIp;
	}

	/** 
	 *set clientIp
	 * @param clientIp 
	 * @author lvzf 2016年9月5日
	 */
	public void setClientIp(String clientIp) {
		this.clientIp = clientIp;
	}

	/**
	 * get ipAddr  
	 * @return   
	 * @author lvzf 2016年9月5日
	 */
	public String getIpAddr() {
		return ipAddr;
	}

	/** 
	 *set ipAddr
	 * @param ipAddr 
	 * @author lvzf 2016年9月5日
	 */
	public void setIpAddr(String ipAddr) {
		this.ipAddr = ipAddr;
	}

	/**
	 * get ygProduct  
	 * @return   
	 * @author lvzf 2016年9月25日
	 */
	public YgProductEntity getYgProduct() {
		return ygProduct;
	}

	/** 
	 *set ygProduct
	 * @param ygProduct 
	 * @author lvzf 2016年9月25日
	 */
	public void setYgProduct(YgProductEntity ygProduct) {
		this.ygProduct = ygProduct;
	}
 
	
}

src/main/java/cn/com/yyg/front/web/member/controller/MemberBuyController.java
package cn.com.yyg.front.web.member.controller;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import cn.com.easy.exception.BusinessException;
import cn.com.yyg.base.entity.PayRecordEntity;
import cn.com.yyg.base.entity.UserEntity;
import cn.com.yyg.base.entity.YgCartEntity;
import cn.com.yyg.front.dao.UserDao;
import cn.com.yyg.front.dao.YgCartDao;
import cn.com.yyg.front.dao.YgProductDao;
import cn.com.yyg.front.service.PayService;
import cn.com.yyg.front.service.ScoreService;
import cn.com.yyg.front.service.UserService;
import cn.com.yyg.front.service.YgBuyService;
import cn.com.yyg.front.utils.RequestUtils;
import cn.com.yyg.front.web.pub.controller.PubCartController;
import cn.com.yyg.front.web.pub.dto.CartDto;

import com.google.common.collect.Lists;

@Controller
@RequestMapping("/member/buy")
public class MemberBuyController {
	private Logger logger = LoggerFactory.getLogger(MemberBuyController.class);
	/** 云购购物车 */
	@Autowired
	private YgCartDao ygCartDao; 
	/** 云购 */
	@Autowired
	private YgProductDao ygProductDao;
	@Autowired
	private UserDao userDao;
	@Autowired
	private YgBuyService ygBuyService;
	@Autowired
    private PayService payService;
	/**积分 */
	@Autowired
	private ScoreService scoreService;
	@Autowired
	private UserService userService;
	@Autowired
	private PubCartController pubCartController;
	@RequestMapping(value = "/paycheck", method = RequestMethod.POST)
	public String checkout(ModelMap modelMap, HttpServletRequest req, HttpServletResponse res,Long[] ids){
		UserEntity user=userDao.findOne(RequestUtils.getCurrentUser(req).getId());
		List<YgCartEntity> list=ygCartDao.findByUserIdAndYgProductIdIn(user.getId(), Lists.newArrayList(ids));
		Map<Long,CartDto> cartMap=new LinkedHashMap<Long,CartDto>(); 
		for(YgCartEntity y:list){
			CartDto dto=new CartDto(y.getYgProductId(),y.getBuyNum());
			dto.setUpdateDate(y.getLastModifyTime().getTime());
			cartMap.put(y.getYgProductId(),dto);
		}
		List<CartDto> results= pubCartController.getCartList(modelMap, req, res,cartMap);
		long totalPrice=0;
		for(CartDto c:results){
			if(c.isSuccess()){
				totalPrice+=c.getBuyNum()*c.getProduct().getSinglePrice();
			}
		}
		modelMap.addAttribute("results", results);
		modelMap.addAttribute("totalPrice", totalPrice);
		modelMap.addAttribute("accountBalance", user.getAccountBalance());
		return "/pub/buy/pay_check";
	}
	/**
	 * 立即支付
	 *@param modelMap
	 *@param req
	 *@param res
	 *@param accountBalancePay 是否账户余额支付
	 *@param ids 云购商品id
	 *@return
	 * @author lvzf 2016年8月27日
	 */
	@RequestMapping(value = "/paySubmit", method = RequestMethod.POST)
	public String pay(ModelMap modelMap, HttpServletRequest req, HttpServletResponse res,int payType,Long[] ids){
		try{
			if(ids==null || ids.length==0){
				throw new BusinessException("没有选择商品");
			}
			UserEntity user=userDao.findOne(RequestUtils.getCurrentUser(req).getId());			
			modelMap.addAttribute("user", user);	
			PayRecordEntity pay=ygBuyService.createPayOrder(user, payType, Lists.newArrayList(ids));
			//余额支付
			if(payType==PayRecordEntity.PAY_TYPE_YUE){
				if(user.getAccountBalance().longValue()<pay.getAmount().longValue()){
					throw new BusinessException("账号余额不足");
				}
				//生成中奖号码
				ygBuyService.createWinNo(user,pay);
				RequestUtils.setCurrentUser(req, user);
			}//支付宝支付
			else if(payType==PayRecordEntity.PAY_TYPE_ALI){
				return "redirect:/alipay.html?payNo="+pay.getPayNo();
			}//微信扫码支付
			else if(payType==PayRecordEntity.PAY_TYPE_WX){
				return "redirect:/wxPay/createQrcode.html?payNo="+pay.getPayNo();
			}

		}catch(BusinessException e){ 
			modelMap.addAttribute("message", e.getMessage());
			return "/pub/buy/pay_error";  
		}catch(Exception e){
			logger.error("支付错误：", e);
			modelMap.addAttribute("message", "未知错误");
			return "/pub/buy/pay_error"; 
		}
		return "/pub/buy/pay_result";
	}
	/**
	 * 支付
	 *@param modelMap
	 *@param req
	 *@param res
	 *@param payNo
	 *@return
	 * @author lvzf 2016年10月8日
	 */
	@RequestMapping(value = "/pay")
	public String pay(ModelMap modelMap, HttpServletRequest req, HttpServletResponse res,String payNo){
		try{
			UserEntity user=userDao.findOne(RequestUtils.getCurrentUser(req).getId());			
			modelMap.addAttribute("user", user);	
			PayRecordEntity pay=payService.getPayByPayNo(payNo); 
			if(pay==null || pay.getPayStatus()!=PayRecordEntity.PAY_STATUS_INIT){ 
				throw new BusinessException("该订单已经支付或取消");
			} 
			int payType =pay.getPayType();
			//余额支付
			if(payType==PayRecordEntity.PAY_TYPE_YUE){
				if(user.getAccountBalance().longValue()<pay.getAmount().longValue()){
					throw new BusinessException("账号余额不足");
				} 
				//生成中奖号码
				ygBuyService.createWinNo(user,pay);
			}//支付宝支付
			else if(payType==PayRecordEntity.PAY_TYPE_ALI){
				return "redirect:/alipay.html?payNo="+pay.getPayNo();
			}//微信扫码支付
			else if(payType==PayRecordEntity.PAY_TYPE_WX){
				return "redirect:/wxPay/createQrcode.html?payNo="+pay.getPayNo();
			}

		}catch(BusinessException e){ 
			modelMap.addAttribute("message", e.getMessage());
			return "/pub/buy/pay_error";  
		}catch(Exception e){
			logger.error("支付错误：", e);
			modelMap.addAttribute("message", "未知错误");
			return "/pub/buy/pay_error"; 
		}
		return "/pub/buy/pay_result";
	}
	/**
	 * 支付成功返回页面
	 *@param modelMap
	 *@param req
	 *@param res
	 *@param payNo
	 *@return
	 * @author lvzf 2016年9月22日
	 */
	@RequestMapping(value = "/payResult")
	public String payResult(ModelMap modelMap, HttpServletRequest req, HttpServletResponse res,String payNo){
		UserEntity user=RequestUtils.getCurrentUser(req);
		modelMap.addAttribute("user", user);
		return "/pub/buy/pay_result";
	}
}

src/main/webapp/WEB-INF/pages/member/order/order_list.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<%@ include file="../../pub/commons/commons_resource_head.jsp"%>
<title>幸运记录_${comName}</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link rel="stylesheet" type="text/css" href="${mimeBase}/styles/member/member_common.css" />
<link rel="stylesheet" type="text/css" href="${mimeBase}/styles/member/member.css" />
<style type="text/css">
.hy-btn2,.hy-btn1{     text-decoration: none;background:#e54048; height:22px; border:none; font-size:14px; color:#fff; cursor:pointer; -moz-border-radius:5px;    -webkit-border-radius:5px; border-radius:5px; padding:0 15px; font-family: Microsoft Yahei, Arial, Verdana, sans-serif }

</style>
</head>
<body>
 <%@ include file="../../pub/index/index_head.jsp"%>
 <div class="g-body">
  <div class="m-user" id="pro-view-0" module-id="module-1" module-launched="true">
   <div class="g-wrap">
    <div class="m-user-frame-wraper">
     <c:set var="member_nav" value="order" />
     <%@ include file="../member_left.jsp"%>
     <div class="m-user-frame-colMain ">
      <div class="m-user-frame-content" pro="userFrameWraper">
       <ul class="w-crumbs f-clear">
        <li class="w-crumbs-item">当前位置：</li>
        <li class="w-crumbs-item"><a href="/member/">我的夺宝</a><span class="w-crumbs-split">&gt;</span></li>
        <li class="w-crumbs-item w-crumbs-active">我的订单</li>
       </ul>
        <div class="m-user-duobao">

         <!-- begin right main  -->
         <div class="m-user-comm-wraper">
          <div class="m-user-duobao">
           <div class="m-user-comm-cont m-user-duobaoOther" id="pro-view-10" module-id="module-8" module-launched="true">
             <div class="m-user-comm-title">
              <div class="m-user-comm-navLandscape">
               <a class="i-item <c:if test="${empty param.status }">i-item-active</c:if>" href="/member/order.html">
                所有订单
                <span pro="tagNum_join"></span>
               </a>
               <span class="i-sptln">|</span>
               <a class="i-item <c:if test="${ param.status ==1}">i-item-active</c:if>" data-name="multi" href="/member/order.html?status=1">
                待发货
                <span class="txt-impt" pro="tagNum_multi"></span>
               </a>
               <span class="i-sptln">|</span>
               <a class="i-item <c:if test="${ param.status ==2}">i-item-active</c:if>" data-name="willReveal" href="/member/order.html?status=2">
                待收货
                <span class="txt-impt" pro="tagNum_willReveal"></span>
               </a>
               <span class="i-sptln">|</span>
               <a class="i-item <c:if test="${ param.status ==3}">i-item-active</c:if>" data-name="periodRevealed" href="/member/order.html?status=3">
                完成
                <span class="txt-impt" pro="tagNum_periodRevealed"></span>
               </a>
              </div>
             </div>
           <c:choose>
          <c:when test="${page.totalItems==0 }">
           <div class="m-win m-win-myself" module-id="module-3" module-launched="true">
            <div>
             <div class="m-user-comm-empty">
              <b class="ico ico-face-sad"></b>
              <div class="i-desc">您还没有此记录哦~</div>
              <div class="i-opt">
               <a href="/" class="w-button w-button-main w-button-xl">马上试试运气</a>
              </div>
             </div>
            </div>
           </div>
          </c:when>
          <c:otherwise>
             <div pro="container">
             <div class="listCont" data-name="join" style="display: block;">
              <div id="pro-view-17">
               <table class="w-table m-user-comm-table" pro="listHead">
                <thead>
                 <tr>
                  <th class="col-info">订单信息</th>
                  <th class="col-info">商品信息</th>
                  <th class="col-info">收货信息</th> 
                  <th class="col-opt">操作</th>
                 </tr>
                </thead>
               </table>
               <div pro="duobaoList" class="duobaoList">
                <c:forEach items="${page.result }" var="item">
                 <table class="m-user-comm-table" id="pro-view-18">
                  <tbody>
                   <tr>
                    <td class="col-info">
                    订单号：${item.orderId }<Br/>
                    下单时间：<fmt:formatDate value="${item.createTime }" pattern="yyyy-MM-dd HH:mm:ss" />
                    </td>
                    <td class="col-info">
                     <div class="w-goods w-goods-l w-goods-hasLeftPic">
                      <div class="w-goods-pic">
                       <a target="_blank" href="/product/${item.ygProduct.id}.html">
                        <img src="${item.ygProduct.logoPath }" alt="${item.ygProduct.name}" width="74" height="74">
                       </a>
                      </div>
                      <p class="w-goods-title f-txtabb" style="    padding-top: 15px;">
                       <a title="${item.ygProduct.name}" target="_blank" href="/product/${item.ygProduct.id}.html">(第${item.ygProduct.period }期) ${item.ygProduct.name}</a>
                      </p>
                      <p class="w-goods-price">金额：￥${item.ygProduct.totalNum } </p> 
                     </div>
                    </td>
                    <td class="col-info">
                    ${item.address.provinceName } ${item.address.cityName } ${item.address.areaInfo }&nbsp;&nbsp;${item.address.trueName }&nbsp;&nbsp;${item.address.mobile }
                      <c:if test="${not empty item.expNo }">
                        <br/>
                        顺丰快递单号: 2222<br/>
                       <a class="color02" href="${item.expressCom.url}?mscomnu=${item.expNo}" target="_blank">查看物流</a>
                       </c:if>
                     </td>
                    <td class="col-opt"> 
                      <span class="color01">${item.statusName }</span>
                      <c:if test="${item.status == 2}">
                      <br/><a href="javascript:;" onclick="accept_confirm('您确认已经收到该商品？',${item.id})" class="hy-btn2">确认收货</a>
                      </c:if>
                      <c:if test="${(item.status == 2 || item.status == 3) && empty item.shareId}">
                      <br/>
                         <a href="/member/share/pre_save/${item.id}"   class="hy-btn2">晒单</a>
                      </c:if>
                      <c:if test="${not empty item.shareId}">
                      <br/>
                         <a href="/share/${item.shareId}.html"   class="hy-btn2">查看晒单</a>
                      </c:if>
                    </td>
                   </tr>
                  </tbody>
                 </table>
                </c:forEach>
               </div>
                <div style="width:100%;text-align:center">
                 <%@ include file="../../pub/commons/page.jsp"%>
                <script type="text/javascript">
                 $(".w-pager button").click(function() {
                   window.location="/member/win.html?pageNo="+$(this).attr("pageNo");
                 });
                </script>
                </div>
              </div>
             </div>
            </div>            
            </c:otherwise>
            </c:choose>
           </div>
          </div>
         </div>
          <!-- end right main -->
        </div>
      </div>
       <div class="m-user-frame-clear"></div>
    </div>
   </div>
  </div>
  </div>
      <%@ include file="../../pub/index/index_foot.jsp"%>
       <script type="text/javascript">
              function viewBuyRecord(userId,ygProductId){
            	    jQuery.post("/member/viewBuyRecord.html", {"ygProductId" : ygProductId}, function(data) {
                        $(document.body).append(data);
                        var wnd = $(window), doc = $(document);
                        var left = doc.scrollLeft();
                        var top = doc.scrollTop();
                        var dialog=$("#db-view-dialog");
                        left += (wnd.width() - dialog.width())/2;
                        top = (wnd.height() -dialog.height())/2;                    
                        dialog.css("top",top);
                        dialog.css("left",left); 
                        
                        //查看号码窗口关闭
                        $('.w-msgbox-close').click(function(){
                            $('#db-view-mask,#db-view-dialog').remove();
                        });
                    });
              }
              function accept_confirm(title,id){
            	  if(confirm(title)){
            		// 异步请求
      				$.ajax({
      					type : "GET",
      					cache : false,
      					dataType : "json",
      					url : "/member/order/sureAccept.json?orderId=" +id,
      					success : function(data) {
      						 window.location= window.location.href;
      					}
      				});
            	  }
              }
       </script>
    </div>
</body>
</html>